import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import useSWR from 'swr'

import { Button } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Mail() {
  const [shouldSendMail, setShouldSendMail] = useState(false)
  const { data } = useSWR(shouldSendMail ? '/api/send-mail' : null, fetcher, {
    revalidateOnFocus: false,
    revalidateOnReconnect: false,
    refreshWhenOffline: false,
    refreshWhenHidden: false,
    refreshInterval: 0,
  })
  console.log(data)

  function handleMailSend() {
    setShouldSendMail(true)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SendGrid Spike</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spikes.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Correo a través de SendGrid! 📧</h1>
        <Button onClick={handleMailSend} colorScheme="blue" mt={4}>
          Enviar correo
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
